name: Bug Report
description: Report a bug or issue with the SPI Customizer system
title: "Bug: [Brief description of the issue]"
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Thank you for reporting a bug! Please provide detailed information to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug you encountered
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: "1. Go to...
2. Click on...
3. See error..."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: "Describe what you expected to see or happen"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Describe what actually occurred"
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this bug?
      options:
        - Low (cosmetic issue, workaround exists)
        - Medium (functional issue with workaround)
        - High (functional issue, no workaround)
        - Critical (system-breaking issue)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of SPI Customizer are you using?
      placeholder: "e.g., v1.0, commit hash, or 'latest'"
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Your operating system, Python version, etc.
      placeholder: "e.g., Ubuntu 20.04, Python 3.9, Docker"
    validations:
      required: false

  - type: checkboxes
    id: components
    attributes:
      label: Affected Components
      description: Which parts of the system are affected?
      options:
        - label: Web Interface
        - label: Configuration Parser
        - label: Verilog Generator
        - label: RTL Simulator
        - label: Email System
        - label: GitHub Workflow
        - label: Documentation

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Screenshots
      description: Include any error messages, logs, or screenshots
      placeholder: "Paste error logs here or describe what you saw"
    validations:
      required: false

  - type: input
    id: email
    attributes:
      label: Email Address
      description: Your email for follow-up (optional)
      placeholder: "your-email@example.com"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might help
      placeholder: "Add any other context about the problem here"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Next Steps

        1. 🐛 Our team will review your bug report
        2. 🔍 We'll investigate the issue and try to reproduce it
        3. 🛠️ If confirmed, we'll work on a fix
        4. 📧 We'll update you via email (if provided) or this issue
        5. ✅ Once fixed, this issue will be closed

        **Thank you for helping improve SPI Customizer!**
