blank_issues_enabled: false
contact_links:
  - name: SPI Customizer Documentation
    url: https://github.com/SJTU-YONGFU-RESEARCH-GRP/spi-customizer/blob/main/README.md
    about: Read the documentation for the SPI Customizer system
