blank_issues_enabled: false
contact_links:
  - name: SPI Customizer Documentation
    url: https://github.com/SJTU-YONGFU-RESEARCH-GRP/spi-customizer/blob/main/README.md
    about: Read the documentation for the SPI Customizer system
  - name: SPI Request Issue
    url: https://github.com/SJTU-YONGFU-RESEARCH-GRP/spi-customizer/.github/ISSUE_TEMPLATE/issue_template.md
    about: Create a new SPI request issue
