blank_issues_enabled: true
contact_links:
  - name: SPI Customizer Documentation
    url: https://github.com/SJTU-YONGFU-RESEARCH-GRP/spi-customizer/blob/main/README.md
    about: Read the documentation for the SPI Customizer system
  - name: Report Bug or Request Feature
    url: https://github.com/SJTU-YONGFU-RESEARCH-GRP/spi-customizer/issues/new
    about: Create a bug report or feature request
