blank_issues_enabled: false
contact_links:
  - name: SPI Customizer Documentation
    url: https://github.com/SJTU-YONGFU-RESEARCH-GRP/spi-customizer/blob/main/README.md
    about: Read the documentation for the SPI Customizer system
  - name: Feature Request
    url: https://github.com/SJTU-YONGFU-RESEARCH-GRP/spi-customizer/issues/new?template=spi-config-form.yml
    about: Request a new SPI configuration or feature
  - name: Bug Report
    url: https://github.com/SJTU-YONGFU-RESEARCH-GRP/spi-customizer/issues/new
    about: Report a bug or issue with the SPI Customizer
