name: Feature Request
description: Request a new feature or enhancement for the SPI Customizer system
title: "Feature: [Brief description of the feature]"
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Thank you for suggesting a new feature! Please provide detailed information to help us understand and implement your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see implemented
      placeholder: "What feature would you like to add? What problem does it solve?"
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature?
      placeholder: "Describe the specific scenario where this feature would be useful"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this feature should work?
      placeholder: "Describe how you envision this feature working"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (useful enhancement)
        - High (important improvement)
        - Critical (essential feature)
    validations:
      required: true

  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - label: New SPI configuration options
        - label: Enhanced testing capabilities
        - label: Improved user interface
        - label: Better error handling
        - label: Performance improvements
        - label: Documentation enhancements
        - label: Integration with other tools
        - label: Other (please specify)

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: "What other approaches have you thought about?"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might help
      placeholder: "Add any other context, screenshots, or examples here"
    validations:
      required: false

  - type: input
    id: email
    attributes:
      label: Email Address
      description: Your email for follow-up on this feature request (optional)
      placeholder: "your-email@example.com"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Next Steps

        1. 💡 Our team will review your feature request
        2. 📊 We'll assess feasibility and impact
        3. 🎯 If approved, we'll add it to our development roadmap
        4. 📧 We'll update you via email (if provided) or this issue
        5. 🚀 Once implemented, this issue will be closed

        **Thank you for helping improve SPI Customizer!**
