name: SPI Configuration Request
description: Request a custom SPI (Serial Peripheral Interface) configuration with specific technical parameters
title: "SPI Config: [Brief description of your configuration]"
labels: ["spi-customization", "enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## SPI Configuration Request

        Please provide the following details for your custom SPI configuration:
  - type: input
    id: spi-mode
    attributes:
      label: SPI Mode
      description: Enter SPI mode (0, 1, 2, or 3)
      placeholder: "0, 1, 2, or 3"
    validations:
      required: true
  - type: input
    id: data-width
    attributes:
      label: Data Width
      description: Number of bits (8, 16, 32, or custom)
      placeholder: "8, 16, 32, or custom number"
    validations:
      required: true
  - type: input
    id: num-slaves
    attributes:
      label: Number of Slaves
      description: Number of slave devices (1, 2, 4, 8, or custom)
      placeholder: "1, 2, 4, 8, or custom"
    validations:
      required: true
  - type: dropdown
    id: slave-select
    attributes:
      label: Slave Select Behavior
      description: Select the slave select polarity
      options:
        - Active Low (most common)
        - Active High
    validations:
      required: true
  - type: dropdown
    id: data-order
    attributes:
      label: Data Order
      description: Select the data transmission order
      options:
        - MSB First (most common)
        - LSB First
    validations:
      required: true
  - type: checkboxes
    id: special-features
    attributes:
      label: Special Features
      description: Select any additional features needed
      options:
        - label: Interrupt Support
        - label: FIFO Buffers
        - label: DMA Support
        - label: Multi-master Support
  - type: dropdown
    id: test-duration
    attributes:
      label: Testing Requirements
      description: Select the level of testing required
      options:
        - Brief
        - Standard
        - Comprehensive
    validations:
      required: true
  - type: checkboxes
    id: testing-options
    attributes:
      label: Testing Options
      description: Select additional testing options
      options:
        - label: Clock Jitter Testing (tests timing margins)
        - label: Waveform Capture (generates detailed timing diagrams)
  - type: input
    id: email
    attributes:
      label: Email Address
      description: Your email address for receiving results
      placeholder: "your-email@example.com"
    validations:
      required: true
  - type: input
    id: github-username
    attributes:
      label: GitHub Username
      description: Your GitHub username for issue updates
      placeholder: "your-username"
    validations:
      required: true
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any additional requirements, constraints, or specific use cases
      placeholder: "Provide any additional requirements, constraints, or specific use cases for this SPI configuration"
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## What Happens Next?

        1. 🤖 The automation system will parse your configuration
        2. 🔧 Custom Verilog code will be generated for your specifications
        3. 🧪 The design will be tested with comprehensive testbenches
        4. 📊 Timing diagrams and performance plots will be created
        5. 📧 Results will be emailed to you with downloadable files
        6. ✅ This issue will be updated with the results and then closed

        **Expected completion time: 5-10 minutes**
