name: Test SPI Request
description: Test form to verify GitHub issue forms work correctly
title: "Test: SPI Configuration"
labels: ["test"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # Test SPI Configuration

        This is a test form to verify that GitHub issue forms are working correctly.
  - type: input
    id: spi-mode
    attributes:
      label: SPI Mode
      description: Enter SPI mode for testing
      placeholder: "0, 1, 2, or 3"
    validations:
      required: true
  - type: input
    id: data-width
    attributes:
      label: Data Width
      description: Number of bits for testing
      placeholder: "8, 16, 32"
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email
      description: Your email address for test notifications
      placeholder: "your-email@example.com"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        If you can see this form and fill it out, then the system is working correctly!
